### ISSUE TITLE
FeedProfile type missing in 3.x

### ISSUE THREAD

**Issue by Soulusions** [drasticactions/FishyFlip#137]
Hello!
Problem is quite self-explanatory, I've upgraded to the 3.1.2 version of the nuget package, and the FeedProfile type seems to be gone.
I find this odd since I can still see it in the latest API docs, so I'm assuming this is just some source gen going wrong.
I didn't dive super deep into this, so there may be more missing.

Thanks a lot for the work on this library all the same though, been enjoying using it : )

**Comment by drasticactions** [comment]
That's a breaking change as part of 3.x. It's intentional to match the Lexicon, so some of the names had to be broken to make it easier to generate.

So FeedProfile became [ProviewViewDetailed](https://drasticactions.github.io/FishyFlip/api/FishyFlip.Lexicon.App.Bsky.Actor.ProfileViewDetailed.html?q=ProfileViewDetailed). It's the same thing, but with a different name and more types on it. I need to remove the generated API site from the source here, since it's generated and not deployed from the repo itself. 

https://github.com/drasticactions/FishyFlip/blob/7008c88186adccd67a447fa6c7899ef6e1e80e9f/src/FishyFlip/Lexicon/App/Bsky/Actor/ProfileViewDetailed.g.cs#L141

The source generation is literally everything within the [lexicon](https://github.com/bluesky-social/atproto/tree/main/lexicons).

**Comment by Soulusions** [comment]
Oh okay yeah this makes sense then, I actually changed all FeedProfile instances to ProfileViewDetailed in the first place as a quick fix lol.
It's just that the fact it was still in the docs made me think something went wrong, if it's intentional, then I've had 0 problems with just going for a ProfileViewDetailed!

**Comment by drasticactions** [comment]
I've removed the generated docs from the repo (https://github.com/drasticactions/FishyFlip/commit/046b2c63f99936160a56815107c8ff951fa0abf5). I totally didn't think about that so if you did search in GitHub you would see the old names and not the generated ones on the website. 

Thanks for letting me know, sorry about that!
