### ISSUE TITLE
AutoRenewSession does not seem to work correctly

### ISSUE THREAD

**Issue by UpcraftLP** [drasticactions/FishyFlip#3]
I have configured `EnableAutoRenewSession(true)` in the ATProtocol builder, so I would expect that if I receive an `ExpiredToken` error the client reauthenticates and resends the request;
However, instead the result is being propagated and not being handled automatically.
```
FishyFlip.Tools.ATNetworkErrorException: 400: ErrorDetail { Error = ExpiredToken, Message = Token has expired }
          at FishyFlip.Tools.ResultExtensions.HandleResult[T](Result`1 result) in /home/runner/work/FishyFlip/FishyFlip/src/FishyFlip/Tools/ResultExtensions.cs:line 23
```

**Comment by drasticactions** [comment]
This should be fixed by https://github.com/drasticactions/FishyFlip/commit/388f376b25dfe88bc425d6ca9094ca2ea9d69737

I mixed up the tokens and used Refresh when I should have used Access. Now the time to renew should be correct. I also updated it so if you pass in an already expired token, it should refresh without setting the timer, then when it refreshes will set the timer from that point on.

It's in https://www.nuget.org/packages/FishyFlip/1.1.52-alpha. Try it and let me know if it works for you.

**Comment by UpcraftLP** [comment]
Thank you, I'll try over the next few days and see whether it works ^^

**Comment by UpcraftLP** [comment]
Yup, seems fixed now!

Sadly still having issues with the websocket not reconnecting after cloudflare randomly terminates it, but, the original error is gone now.

**Comment by drasticactions** [comment]
EnableAutoRenewSession was only for ATProtocol itself for handling tokens. It never touched the websocket connections. But that sounds like a good idea: https://github.com/drasticactions/FishyFlip/issues/5

**Comment by UpcraftLP** [comment]
Yup!
