### ISSUE TITLE
Handling Bsky PDS/BGS split

### ISSUE THREAD

**Issue by UpcraftLP** [drasticactions/FishyFlip#4]
with the main firehose + some other api routes being moved to the BGS instead of PDS, there probably should be a way to configure the api client and tell it which routes go where.

see ex.
https://bsky.app/profile/did:plc:tpg43qhh4lw4ksiffs4nbda3/post/3kazfyia23k2y

**Comment by drasticactions** [comment]
I was aware of it, yes. If you set the BGS address as your instance URL when creating an `ATProtocol` you should be able to connect to it normally. You can spin up as many `ATProtocol` instances as you like, and they can point to whatever you want.

It would probably make more sense to spin off `ATWebSocketProtocol` outside of `ATProtocol` instead of introducing an option for different addresses. They are not tightly coupled and you could spin up N amount of protocols for multiple firehoses.

**Comment by drasticactions** [comment]
https://github.com/drasticactions/FishyFlip/commit/2f2a6a32d5d41fd6e0a14465a84f02a145cfabbd

https://www.nuget.org/packages/FishyFlip/1.1.54-alpha

- Made ATWebSocketProtocol public
- Added ATWebSocketProtocolBuilder for creating a new ATWebSocketProtocol.
- The existing WebSocket methods in `ATProtocol` are now obsolete. They will still work and call the underlying ATWebSocketProtocol, but you should make a separate one instead.

This should allow for a better separation of firehose systems with protocol handlers.

**Comment by drasticactions** [comment]
Closing this with the implementation I added above. If you have issues connecting to the BGS with it, feel free to reopen this or create a new issue. Thanks!
